#ifndef __PINS_DEF
#define __PINS_DEF
/****************************************************************/
/** AUTOGENERATED from ../include/pins.def. DO NOT EDIT *********/
/****************************************************************/

#if defined(STM32L1) && defined(OPENCM3)
#  include <stm32l1_opencm3_pins.h>
#elif defined(STM32L1) &&  defined(STM32_STDPERIPH_LIB)
#  include <stm32l1_stdperiphlib_pins.h>
#elif defined(TESTING)
#  include <empty_pins.h>
#else
#  error "Unsupprted architecture"
#endif
#define PIEZO_OUT_TIMER                 TIM4
#define PIEZO_OUT_CHANNEL               TIM_OC(4)
#define PIEZO_OUT_AF                    GPIO_AF2
#define STATUS_LED_TIMER                TIM2
#define STATUS_LED_CHANNEL              TIM_OC(4)
#define STATUS_LED_AF                   GPIO_AF1
#define BT_STORE                        SPI1
#define BT_STORE_GPIO                   GPIO(A)
#define BT_STORE_PINS                   (PIN(7)|PIN(6)|PIN(5))
#define SENSORS                         SPI2
#define SENSORS_GPIO                    GPIO(B)
#define SENSORS_PINS                    (PIN(15)|PIN(14)|PIN(13))
#define UBLOX_UART                      USART1
#define UBLOX_UART_GPIO                 GPIO(A)
#define UBLOX_UART_PINS                 (PIN(10)|PIN(9))
#define NRF8001_LSB                     1
#define NRF8001_BUS                     BT_STORE
#define ADESTO_FLASH_LSB                1
#define ADESTO_FLASH_BUS                BT_STORE
#define MS5611_LSB                      1
#define MS5611_BUS                      SENSORS
#define BMX055_LSB                      1
#define BMX055_BUS                      SENSORS
#define UBLOX_MAX7_LSB                  1
#define UBLOX_MAX7_BUS                  UBLOX_UART
#define ADESTO_FLASH_CS                 PIN(0)
#define ADESTO_FLASH_CS_GPIO            GPIO(A)
#define ADESTO_FLASH_RESET              PIN(1)
#define ADESTO_FLASH_RESET_GPIO         GPIO(A)
#define NRF8001_RST                     PIN(2)
#define NRF8001_RST_GPIO                GPIO(A)
#define NRF8001_RDYN                    PIN(3)
#define NRF8001_RDYN_GPIO               GPIO(A)
#define NRF8001_REQN                    PIN(4)
#define NRF8001_REQN_GPIO               GPIO(A)
#define BT_STORE_SCK                    PIN(5)
#define BT_STORE_SCK_GPIO               GPIO(A)
#define BT_STORE_MISO                   PIN(6)
#define BT_STORE_MISO_GPIO              GPIO(A)
#define BT_STORE_MOSI                   PIN(7)
#define BT_STORE_MOSI_GPIO              GPIO(A)
#define MS5611_EN                       PIN(8)
#define MS5611_EN_GPIO                  GPIO(A)
#define UBLOX_UART_TX                   PIN(9)
#define UBLOX_UART_TX_GPIO              GPIO(A)
#define UBLOX_UART_RX                   PIN(10)
#define UBLOX_UART_RX_GPIO              GPIO(A)
#define BMX055_EN_ACC                   PIN(0)
#define BMX055_EN_ACC_GPIO              GPIO(B)
#define BMX055_EN_GYRO                  PIN(1)
#define BMX055_EN_GYRO_GPIO             GPIO(B)
#define BMX055_EN_MAG                   PIN(2)
#define BMX055_EN_MAG_GPIO              GPIO(B)
#define CHG                             PIN(4)
#define CHG_GPIO                        GPIO(B)
#define PG                              PIN(5)
#define PG_GPIO                         GPIO(B)
#define WARN_LED_A                      PIN(6)
#define WARN_LED_A_GPIO                 GPIO(B)
#define WARN_LED_B                      PIN(7)
#define WARN_LED_B_GPIO                 GPIO(B)
#define PIEZO_EN                        PIN(8)
#define PIEZO_EN_GPIO                   GPIO(B)
#define PIEZO_OUT                       PIN(9)
#define PIEZO_OUT_GPIO                  GPIO(B)
#define NRF8001_ACTIVE                  PIN(10)
#define NRF8001_ACTIVE_GPIO             GPIO(B)
#define STATUS_LED                      PIN(11)
#define STATUS_LED_GPIO                 GPIO(B)
#define BATT_SENSE                      PIN(12)
#define BATT_SENSE_GPIO                 GPIO(B)
#define SENSORS_SCK                     PIN(13)
#define SENSORS_SCK_GPIO                GPIO(B)
#define SENSORS_MISO                    PIN(14)
#define SENSORS_MISO_GPIO               GPIO(B)
#define SENSORS_MOSI                    PIN(15)
#define SENSORS_MOSI_GPIO               GPIO(B)
#define UBLOX_MAX7_RESET                PIN(13)
#define UBLOX_MAX7_RESET_GPIO           GPIO(C)
#define UBLOX_MAX7_TIMEPULSE            PIN(0)
#define UBLOX_MAX7_TIMEPULSE_GPIO       GPIO(H)
#define UBLOX_MAX7_EXT_INT              PIN(1)
#define UBLOX_MAX7_EXT_INT_GPIO         GPIO(H)
#endif /* __PINS_DEF */
