#!/usr/bin/env python3

from antlr4 import *
from pin_def import *
import sys
from PinDefinitionLexer import PinDefinitionLexer
from PinDefinitionParser import PinDefinitionParser


class OpenCM3Render(object):
    def __init__(self, f):
        self._f = f
        self._render_header()

    def _render_header(self):
        self._f.write('/***************************************/\n')
        self._f.write('/** AUTOGENERATED. DO NOT EDIT *********/\n')
        self._f.write('/***************************************/\n')

    def render_pin(self, pin):
        self._f.write('#define {0.name:30}  PIN({0.index})\n'.format(pin))
        self._f.write('#define {0:30}  GPIO({1})\n'.format(pin.name+'_GPIO', pin.gpio))

    def render_timer(self, timer):
        n = timer.name
        self._f.write('#define {0:30}  TIM{1}\n'.format(n+'_TIMER', timer.index))
        self._f.write('#define {0:30}  TIM_OC{1}\n'.format(n+'_CHANNEL', timer.channel))
        self._f.write('#define {0:30}  GPIO_AF{1}\n'.format(n+'_AF', timer.af))

class MyGrammarListener(ParseTreeListener):
    def __init__(self, renderer):
        super().__init__()
        self._renderer = renderer
        self._banks = GpioBank()

    def on_pin(self, pin):
        self._banks.add_pin(pin)

    def on_bus(self, bus):
        bus.pins.set_name(bus.name)
        bus.pins.set_gpio(bus.gpio)
        self._banks.add_set(bus.pins)

    def on_peripheral(self, peripheral):
        peripheral.pins.set_name(peripheral.name)
        self._banks.add_set(peripheral.pins)

    def on_timer(self, timer):
        self._renderer.render_timer(timer)

    def enterSpecification(self, ctx):
        for v in ctx.spec:
            if isinstance(v, Pin): self.on_pin(v)
            elif isinstance(v, Bus): self.on_bus(v)
            elif isinstance(v, Peripheral): self.on_peripheral(v)
            elif isinstance(v, Timer): self.on_timer(v)
        self._banks.visit_pins(self._renderer.render_pin)
 

input = FileStream('../include/pins.def')
lexer = PinDefinitionLexer(input)
stream = CommonTokenStream(lexer)
parser = PinDefinitionParser(stream)
tree = parser.specification()

renderer = OpenCM3Render(sys.stdout)
listener = MyGrammarListener(renderer)
walker = ParseTreeWalker()
walker.walk(listener, tree)

